# Generated by Django 3.1 on 2020-08-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map_wc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('info', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=30)),
            ],
        ),
    ]
