# Generated by Django 3.1 on 2020-08-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map_wc',
            name='location',
            field=models.CharField(max_length=40),
        ),
    ]
