# Generated by Django 3.1 on 2020-09-03 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20200830_0247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map_washroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=40)),
                ('x', models.FloatField(default=0.0)),
                ('y', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AlterField(
            model_name='map_wc',
            name='x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='map_wc',
            name='y',
            field=models.FloatField(default=0.0),
        ),
    ]
