# Generated by Django 3.1 on 2020-08-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seouldata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sisulname', models.CharField(max_length=50)),
                ('sisuladdr', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=20)),
            ],
        ),
    ]
