# Generated by Django 3.1 on 2020-09-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datasample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sisulname', models.CharField(max_length=100)),
                ('sisuladdr', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=20)),
                ('lat', models.FloatField(default=0.0)),
                ('lng', models.FloatField(default=0.0)),
                ('kind', models.CharField(max_length=20)),
                ('kind_detail', models.CharField(max_length=30)),
            ],
        ),
    ]
