# Generated by Django 3.1 on 2020-09-01 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_datasample'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasample',
            old_name='sisuladdr',
            new_name='addr',
        ),
        migrations.RenameField(
            model_name='datasample',
            old_name='sisulname',
            new_name='name',
        ),
    ]
