# Generated by Django 3.1 on 2020-09-02 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20200901_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasample',
            old_name='addr',
            new_name='sisuladdr',
        ),
        migrations.RenameField(
            model_name='datasample',
            old_name='name',
            new_name='sisulname',
        ),
        migrations.RemoveField(
            model_name='datasample',
            name='kind_detail',
        ),
        migrations.RemoveField(
            model_name='datasample',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='datasample',
            name='lng',
        ),
    ]
