# Generated by Django 3.1 on 2020-09-03 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_sample'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasample',
            old_name='sisuladdr',
            new_name='addr',
        ),
        migrations.RenameField(
            model_name='datasample',
            old_name='sisulname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='kind_detail',
        ),
    ]
