# Generated by Django 3.1 on 2020-09-03 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_auto_20200903_1520'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sample',
        ),
        migrations.DeleteModel(
            name='Seouldata',
        ),
    ]
