# Generated by Django 3.1 on 2020-09-03 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_auto_20200903_1539'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Datasample',
            new_name='Data',
        ),
    ]
