# Generated by Django 3.1 on 2020-09-03 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_datalist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
