# Generated by Django 3.1 on 2020-09-01 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qnaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qnaboard',
            name='qnawriter',
            field=models.ForeignKey(db_column='userEmail', on_delete=django.db.models.deletion.CASCADE, to='qnaapp.users'),
        ),
    ]
