# Generated by Django 3.1 on 2020-09-01 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qnaapp', '0002_auto_20200901_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='userEmail',
            new_name='useremail',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='nickName',
            new_name='username',
        ),
    ]
