# Generated by Django 3.1 on 2020-09-01 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qnaapp', '0003_auto_20200901_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cwriter', models.ForeignKey(db_column='userEmail', on_delete=django.db.models.deletion.CASCADE, to='qnaapp.users')),
                ('qnaboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qnaapp.qnaboard')),
            ],
        ),
    ]
