# Generated by Django 3.1 on 2020-09-01 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qnaapp', '0004_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='cwriter',
        ),
    ]
