# Generated by Django 3.1 on 2020-09-02 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qnaapp', '0005_remove_answer_cwriter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
