# Generated by Django 3.1 on 2020-09-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnaapp', '0007_qnaboard_admin_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qnaboard',
            name='admin_content',
            field=models.TextField(default=False),
        ),
    ]
