# Generated by Django 3.1 on 2020-09-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnaapp', '0008_auto_20200902_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qnaboard',
            name='admin_content',
            field=models.TextField(),
        ),
    ]
