# Generated by Django 3.1 on 2020-09-03 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnaapp', '0009_auto_20200903_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='qnaboard',
            name='anser_adin',
            field=models.TextField(default=False),
        ),
    ]
