# Generated by Django 3.1 on 2020-09-03 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qnaapp', '0010_qnaboard_anser_adin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qnaboard',
            name='anser_adin',
        ),
    ]
