# Generated by Django 3.0.3 on 2020-09-05 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qnaapp', '0011_remove_qnaboard_anser_adin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Qnaboard',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
