# Generated by Django 3.0.3 on 2020-08-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fordisapp', '0002_article_comment_comment2'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='viewcnt',
            field=models.IntegerField(null=True),
        ),
    ]
