# Generated by Django 3.0.3 on 2020-08-28 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fordisapp', '0003_article_viewcnt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment2',
            old_name='article',
            new_name='comment',
        ),
    ]
