# Generated by Django 3.0.3 on 2020-08-30 23:14

from django.db import migrations, models
import fordisapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('fordisapp', '0006_reportslist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cam',
        ),
        migrations.AlterField(
            model_name='reportslist',
            name='reportPhoto',
            field=models.FileField(blank=True, null=True, upload_to=fordisapp.models.report_upload_to),
        ),
    ]
