# Generated by Django 3.0.3 on 2020-08-31 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fordisapp', '0007_auto_20200831_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comment2',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
