# Generated by Django 3.0.3 on 2020-09-01 02:34

from django.db import migrations, models
import fordisapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('fordisapp', '0008_auto_20200831_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='reportPhoto',
            field=models.FileField(blank=True, null=True, upload_to=fordisapp.models.report_upload_to),
        ),
        migrations.AddField(
            model_name='article',
            name='reportYN',
            field=models.TextField(null=True),
        ),
    ]
