# Generated by Django 3.0.3 on 2020-09-01 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fordisapp', '0009_auto_20200901_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='reportYN',
        ),
        migrations.AddField(
            model_name='article',
            name='boardType',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='reportAddress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='reportLati',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='reportLong',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
