# Generated by Django 3.0.3 on 2020-09-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fordisapp', '0010_auto_20200901_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='reportPhotoId',
            field=models.IntegerField(null=True),
        ),
    ]
