# Generated by Django 3.0.3 on 2020-09-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fordisapp', '0011_article_reportphotoid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='reportPhotoId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
