# Generated by Django 3.0.3 on 2020-09-01 07:12

from django.db import migrations, models
import fordisapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('fordisapp', '0012_auto_20200901_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='reportPhoto',
            field=models.ImageField(blank=True, null=True, upload_to=fordisapp.models.report_upload_to),
        ),
    ]
