# Generated by Django 3.0.3 on 2020-09-01 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fordisapp', '0013_auto_20200901_1612'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportsList',
        ),
    ]
